### ISSUE TITLE
Installation error via npx

### ISSUE THREAD

**Issue by rahulvrane** [entropy-research/Devon#75]
Hi, I seem to be facing some issues installing the ui. Please can I get some help with this?

```

~% curl -sSL https://raw.githubusercontent.com/entropy-research/Devon/main/install.sh | bash
Installing Devon backend...
Installing to existing venv 'devon-agent'
  installed package devon-agent 0.1.15, installed using Python 3.12.4
  These apps are now globally available
    - devon_agent
done! ✨ 🌟 ✨
Devon Backend is installed successfully.
Installing Devon TUI...
devon-tui package is not installed. Installing now...

changed 189 packages in 6s

58 packages are looking for funding
  run `npm fund` for details
Installing Devon UI...

added 580 packages in 2m

175 packages are looking for funding
  run `npm fund` for details
Devon UI is not installed. Please install it manually by running 'npm install -g devon-ui' or 'sudo npm install -g devon-ui'.
~ % npm install -g devon-ui

changed 580 packages in 29s

175 packages are looking for funding
  run `npm fund` for details
~% npx devon-ui
npm error could not determine executable to run
npm error A complete log of this run can be found in: .XXX
```

The error is 

```
0 verbose cli /opt/homebrew/Cellar/node/22.3.0/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.8.1
2 info using node@v22.3.0
3 silly config load:file:/opt/homebrew/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/XX/.npmrc
5 silly config load:file:/opt/homebrew/etc/npmrc
6 verbose title npm exec devon-ui
7 verbose argv "exec" "--" "devon-ui"
8 verbose logfile logs-max:10 dir:/Users/XX/.npm/_logs/2024-06-27T17_08_03_703Z-
9 verbose logfile /Users/XX/.npm/_logs/2024-06-27T17_08_03_703Z-debug-0.log
10 silly logfile start cleaning logs, removing 1 files
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile done cleaning log files
13 http fetch GET 200 https://registry.npmjs.org/devon-ui 750ms (cache revalidated)
14 verbose stack Error: could not determine executable to run
14 verbose stack     at getBinFromManifest (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
14 verbose stack     at exec (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:198:15)
14 verbose stack     at async Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:207:9)
14 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:74:5)
15 verbose pkgid devon-ui@0.0.15
16 error could not determine executable to run
17 verbose cwd /Users/XX
18 verbose os Darwin 23.5.0
19 verbose node v22.3.0
20 verbose npm  v10.8.1
21 verbose exit 1
22 verbose code 1

```

**Comment by ObjectJosh** [comment]
Hey @rahulvrane we just published a new version, try a clean reinstall and let me know if you're still running into this error!

**Comment by endcycles** [comment]
I just now tried to install, same issue. MacOS ARM chip.


```
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 silly logfile done cleaning log files
14 http fetch GET 200 https://registry.npmjs.org/devon-ui 354ms (cache miss)
15 verbose stack Error: could not determine executable to run
15 verbose stack     at getBinFromManifest (/Users/name/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
15 verbose stack     at exec (/Users/name/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:198:15)
15 verbose stack     at async Npm.exec (/Users/name/.nvm/versions/node/v20.5.1/lib/node_modules/npm/lib/npm.js:207:9)
15 verbose stack     at async module.exports (/Users/name/.nvm/versions/node/v20.5.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
16 verbose pkgid devon-ui@0.0.17
17 error could not determine executable to run
18 verbose cwd /Users/name/dev/open-devon
19 verbose os Darwin 23.5.0
20 verbose node v20.5.1
21 verbose npm  v10.8.1
22 verbose exit 1
23 verbose code 1
```

**Comment by akiradev0x** [comment]
Ah, ok I think you need to update npm! @rahulvrane

**Comment by sunny-g** [comment]
@akiradev0x but it seems that npm 10.8.1 is the latest version: https://www.npmjs.com/package/npm?activeTab=versions

**Comment by soberzerg** [comment]
Got the same error, npm version 10.8.1

```
0 verbose cli /Users/sergejsobolev/.nvm/versions/node/v20.13.1/bin/node /Users/sergejsobolev/.nvm/versions/node/v20.13.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.8.1
2 info using node@v20.13.1
3 silly config load:file:/Users/sergejsobolev/.nvm/versions/node/v20.13.1/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/sergejsobolev/ai/agents/Devon/.npmrc
5 silly config load:file:/Users/sergejsobolev/.npmrc
6 silly config load:file:/Users/sergejsobolev/.nvm/versions/node/v20.13.1/etc/npmrc
7 verbose title npm exec devon-ui
8 verbose argv "exec" "--" "devon-ui"
9 verbose logfile logs-max:10 dir:/Users/sergejsobolev/.npm/_logs/2024-06-29T19_25_05_268Z-
10 verbose logfile /Users/sergejsobolev/.npm/_logs/2024-06-29T19_25_05_268Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 silly logfile done cleaning log files
14 http fetch GET 200 https://registry.npmjs.org/devon-ui 1196ms (cache revalidated)
15 verbose stack Error: could not determine executable to run
15 verbose stack     at getBinFromManifest (/Users/sergejsobolev/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
15 verbose stack     at exec (/Users/sergejsobolev/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:198:15)
15 verbose stack     at async Npm.exec (/Users/sergejsobolev/.nvm/versions/node/v20.13.1/lib/node_modules/npm/lib/npm.js:207:9)
15 verbose stack     at async module.exports (/Users/sergejsobolev/.nvm/versions/node/v20.13.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
16 verbose pkgid devon-ui@0.0.18
17 error could not determine executable to run
18 verbose cwd /Users/sergejsobolev/ai/agents/Devon
19 verbose os Darwin 23.5.0
20 verbose node v20.13.1
21 verbose npm  v10.8.1
22 verbose exit 1
23 verbose code 1
24 error A complete log of this run can be found in: /Users/sergejsobolev/.npm/_logs/2024-06-29T19_25_05_268Z-debug-0.log
```

**Comment by sunny-g** [comment]
Fix (if using NVM):
replace `npx devon-ui` with the following adapted for your `node --version`:

```
node ~/.nvm/versions/node/v22.3.0/lib/node_modules/devon-ui/.vite/build/cli.js
```

**Comment by soberzerg** [comment]
It's working, thanks! Btw, nice interface! Excited to see Electron UI

**Comment by akiradev0x** [comment]
oh @sunny-g thanks for that! @soberzerg glad to hear it, closing!

**Comment by akiradev0x** [comment]
Additional solution here is to run npm install -g devon-ui if npx isnt working

**Comment by iilln** [comment]
I have this problem: the model does not work, it takes a long time to display the interface 
![Screenshot 2024-07-15 012241](https://github.com/user-attachments/assets/679e5884-b6f9-4a13-96fe-ecd0cee25e49)
![Screenshot 2024-07-15 012230](https://github.com/user-attachments/assets/df4d3203-ce13-4131-a60d-2fb25b20c2dd)

**Comment by rounakskm** [comment]
On MacOS M2 chip. 

npx devon-ui => npm error could not determine executable to run

AND

npm install -g devon-ui  =>

npm error code ETARGET
npm error notarget No matching version found for @tanstack/virtual-core@3.10.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /Users/ron/.npm/_logs/2024-08-20T03_32_07_322Z-debug-0.log

Is this because of node and npm has been installed using homebrew?
