### ISSUE TITLE
KeyError: 'claude-opus'

### ISSUE THREAD

**Issue by lsc64** [entropy-research/Devon#82]
Originally everything worked but at some point Devon got stuck and wouldn't restart, giving only the following error message (in tui with --debug)

It seems somewhere the model is set to `claude-opus` but it's expected to be `claude-3-5-sonnet` (https://github.com/entropy-research/Devon/blob/2c39a91ed833ab963641bba51cd38501ef47a4b0/devon_agent/agents/conversational_agent.py#L33-L36)

Even manually adjusting .devon.config as follows
```json
{
  "modelName": "claude-3-5-sonnet"
}
```

says it would use sonnet, but still gives the same error

```
╰─$ devon-tui --debug
Using model name: claude-3-5-sonnet
[...]
KeyError: 'claude-opus'
```

Traceback
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/responses.py", line 162, in __call__
    await self.background()
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/background.py", line 45, in __call__
    await task()
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/background.py", line 30, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/devon_agent/session.py", line 328, in run_event_loop
    events = self.step_event(event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/devon_agent/session.py", line 376, in step_event
    thought, action, output = self.agent.predict(
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/devon_agent/agents/conversational_agent.py", line 160, in predict
    self.current_model = self._initialize_model()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dariush/.local/pipx/venvs/devon-agent/lib/python3.12/site-packages/devon_agent/agents/conversational_agent.py", line 54, in _initialize_model
    return self.default_models[self.args.model](
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'claude-opus'
```

**Comment by ObjectJosh** [comment]
@lsc64 you're right. Looks like somewhere in the tui code it didn't update to 3.5 sonnet. Thanks for raising this issue! In the meantime, let me know if the electron app is working for you

**Comment by lsc64** [comment]
> @lsc64 you're right. Looks like somewhere in the tui code it didn't update to 3.5 sonnet. Thanks for raising this issue! In the meantime, let me know if the electron app is working for you

It’s the same for the GUI (electron), I just used the TUI for debugging. (Does —debug work with GUI?)

**Comment by ObjectJosh** [comment]
@lsc64 Hmm... interesting. Have you tried a clean reinstall of both? Haven't gotten this issue with the electron app yet.

**Comment by ObjectJosh** [comment]
Meaning, clean install of `devon_agent` since that's one of the common factors rn

**Comment by Mihir1003** [comment]
I recently pushed an update that fixes this! @lsc64

**Comment by lsc64** [comment]
> I recently pushed an update that fixes this! @lsc64

thanks for the ping @Mihir1003 
Unfortunately I can't try it out, since I'm unable to start devon at al
npx gives me an error
```
0 verbose cli /Users/dariush/.nvm/versions/node/v22.4.1/bin/node /Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.8.1
2 info using node@v22.4.1
3 silly config load:file:/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/dariush/.npmrc
5 silly config load:file:/Users/dariush/.nvm/versions/node/v22.4.1/etc/npmrc
6 verbose title npm exec devon-ui
7 verbose argv "exec" "--" "devon-ui"
8 verbose logfile logs-max:10 dir:/Users/dariush/.npm/_logs/2024-07-15T22_19_31_109Z-
9 verbose logfile /Users/dariush/.npm/_logs/2024-07-15T22_19_31_109Z-debug-0.log
10 silly logfile start cleaning logs, removing 1 files
11 silly logfile done cleaning log files
12 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
13 verbose stack Error: could not determine executable to run
13 verbose stack     at getBinFromManifest (/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
13 verbose stack     at exec (/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:198:15)
13 verbose stack     at async Npm.exec (/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/npm/lib/npm.js:207:9)
13 verbose stack     at async module.exports (/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 verbose pkgid devon-ui@0.0.19
15 error could not determine executable to run
16 verbose cwd /Users/dariush/git/devon
17 verbose os Darwin 23.5.0
18 verbose node v22.4.1
19 verbose npm  v10.8.1
20 verbose exit 1
21 verbose code 1
22 error A complete log of this run can be found in: /Users/dariush/.npm/_logs/2024-07-15T22_19_31_109Z-debug-0.log
```

and running it manually as well

```
╰─$ node ~/.nvm/versions/node/v22.4.1/lib/node_modules/devon-ui/.vite/build/main.js                                            130 ↵
/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/devon-ui/.vite/build/main.js:1
"use strict";var v=Object.defineProperty;var E=(n,t,e)=>t in n?v(n,t,{enumerable:!0,configurable:!0,writable:!0,value:e}):n[t]=e;var f=(n,t,e)=>E(n,typeof t!="symbol"?t+"":t,e);const r=require("electron"),c=require("path"),_=require("child_process"),F=require("portfinder"),l=require("fs"),D=require("fs/promises");function P(n){const t=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});if(n){for(const e in n)if(e!=="default"){const s=Object.getOwnPropertyDescriptor(n,e);Object.defineProperty(t,e,s.get?s:{enumerable:!0,get:()=>n[e]})}}return t.default=n,Object.freeze(t)}const g=P(D),M=require("@parcel/watcher"),O=[".DS_Store","._*",".AppleDouble","Thumbs.db","desktop.ini",".*.swp",".*.swo",".*~","*.tmp","node_modules",".git","__pycache__",".*/"],b=n=>O.some(t=>new RegExp(t.replace(/\./g,"\\.").replace(/\*/g,".*")).test(n));class S{constructor(){f(this,"files");f(this,"openFiles");this.files=new Set,this.openFiles=new Map}async addOpenFile(t){const e=await g.readFile(t,"utf8");this.openFiles.set(t,{path:t,content:e})}handleEvent(t){return t.forEach(e=>{e.type==="create"?this.files.add(e.path):e.type==="delete"&&this.files.delete(e.path),this.openFiles.has(e.path)&&(e.type==="update"?g.readFile(e.path,"utf8").then(s=>{this.openFiles.set(e.path,{path:e.path,content:s})}).catch(s=>{console.error(`Error reading file ${e.path}:`,s)}):e.type==="create"?this.addOpenFile(e.path):e.type==="delete"&&this.openFiles.has(e.path)&&this.openFiles.delete(e.path))}),{files:Array.from(this.files),openFiles:Array.from(this.openFiles.values())}}}let u=new S;r.ipcMain.handle("editor-add-open-file",async(n,t)=>{if(u){if(u.openFiles.has(t))return;await u.addOpenFile(t);const e=u.handleEvent([]);n.sender.send("editor-file-changed",e)}});r.ipcMain.handle("watch-dir",async(n,t)=>{u=new S;const e=async s=>{const o=await g.readdir(s,{withFileTypes:!0}),i=[];for(const a of o){const p=c.join(s,a.name);if(!b(p)&&!p.startsWith("."))if(a.isDirectory())i.push(...await e(p));else try{i.push({type:"create",path:p})}catch(h){console.error(`Error reading file ${p}:`,h)}}return i};try{const s=await e(t);let o=u.handleEvent(s);setTimeout(()=>{n.sender.send("editor-file-changed",o)},1e3);let i=null;const a=await M.subscribe(t,async(p,h)=>{if(p){console.error("Error watching files:",p);return}const w=[];for(const m of h)b(m.path)||w.push(m);i&&clearTimeout(i),i=setTimeout(()=>{o=u.handleEvent(w),n.sender.send("editor-file-changed",o)},500)});return r.ipcMain.once("unsubscribe",()=>{a&&a.unsubscribe()}),!0}catch(s){return console.error("Failed to watch directory:",s),!1}});const j=process.env.DEV_MODE??!1;require("electron-squirrel-startup")&&r.app.quit();let d;F.setBasePort(1e4);let y=NaN;const x=async()=>{const n=c.join(r.app.getPath("userData"));console.log(n),await F.getPortPromise().then(s=>{var o,i;y=s,console.log(n),d=_.spawn("devon_agent",["server","--port",s.toString(),"--db_path",n],{signal:q.signal}),(o=d.stdout)==null||o.on("data",a=>{console.log(`Server: ${a}`)}),(i=d.stderr)==null||i.on("data",a=>{console.error(`Server Error: ${a}`),e&&e.webContents.send("server-error",a.toString())}),d.on("close",a=>{console.log(`Server process exited with code ${a}`)})}).catch(s=>(console.error("Failed to find a free port:",s),{success:!1,message:"Failed to find a free port."}));const t=c.join(__dirname,"preload.js");let e=new r.BrowserWindow({width:800,height:600,titleBarStyle:"hidden",trafficLightPosition:{x:15,y:10},show:!1,webPreferences:{preload:t,contextIsolation:!0,nodeIntegration:!1,additionalArguments:[`--port=${y}`]}});e.loadFile(c.join(__dirname,"../renderer/main_window/index.html")),e.maximize(),e.setMenu(null),e.show(),e.on("closed",()=>{e=null})},A=()=>{new r.BrowserWindow({width:800,height:600,webPreferences:{preload:c.join(__dirname,"preload.js")}}).loadFile(c.join(__dirname,"../renderer/main_window/index.html"))},q=new AbortController;r.app.on("ready",()=>{r.safeStorage.isEncryptionAvailable()?console.log("Encryption is available and can be used."):console.log("Encryption is not available. Fallback mechanisms might be required."),x()});r.app.on("window-all-closed",()=>{r.app.quit()});r.app.on("browser-window-focus",function(){j||(r.globalShortcut.register("CommandOrControl+R",()=>{console.log("CommandOrControl+R is pressed: Shortcut Disabled")}),r.globalShortcut.register("F5",()=>{console.log("F5 is pressed: Shortcut Disabled")}))});r.app.on("browser-window-blur",function(){r.globalShortcut.unregister("CommandOrControl+R"),r.globalShortcut.unregister("F5")});r.app.on("activate",()=>{r.BrowserWindow.getAllWindows().length===0&&A()});r.app.on("window-all-closed",()=>{process.platform!=="darwin"&&r.app.quit()});r.app.on("before-quit",()=>{d.pid&&(console.log("Killing server process with pid",d.pid),process.kill(d.pid,"SIGTERM")),d.kill(9),d.killed?console.log("Server process was successfully killed."):console.log("Failed to kill the server process.")});r.ipcMain.handle("ping",()=>(console.log("PONG!"),"pong"));r.ipcMain.on("get-port",n=>{n.reply("get-port-response",y)});r.ipcMain.on("get-file-path",n=>{r.dialog.showOpenDialog({properties:["openDirectory","createDirectory"]}).then(t=>{!t.canceled&&t.filePaths.length>0?n.reply("file-path-response",t.filePaths[0]):n.reply("file-path-response","cancelled")}).catch(t=>{console.error("Failed to open dialog:",t),n.reply("file-path-response","error")})});r.ipcMain.handle("encrypt-data",async(n,t)=>{try{return r.safeStorage.encryptString(t).toString("hex")}catch(e){throw console.error("Encryption failed:",e),e}});r.ipcMain.handle("decrypt-data",async(n,t)=>{try{const e=Buffer.from(t,"hex");return r.safeStorage.decryptString(e)}catch(e){throw console.error("Decryption failed:",e),e}});r.ipcMain.handle("save-data",async(n,t)=>{if(r.safeStorage.isEncryptionAvailable()){const e=r.safeStorage.encryptString(t),s=c.join(r.app.getPath("userData"),"secureData.bin");l.existsSync(s)||l.writeFileSync(s,"");try{return l.writeFileSync(s,e),{success:!0}}catch(o){return console.error("Failed to save encrypted data:",o),{success:!1,message:"Failed to save encrypted data"}}}else return{success:!1,message:"Encryption not available"}});r.ipcMain.handle("load-data",async()=>{const n=c.join(r.app.getPath("userData"),"secureData.bin");l.existsSync(n)||l.writeFileSync(n,"");try{const t=l.readFileSync(n);return r.safeStorage.isEncryptionAvailable()?{success:!0,data:r.safeStorage.decryptString(t)}:{success:!1,message:"Decryption not available"}}catch(t){return console.error("Failed to read encrypted data:",t),{success:!1,message:"Failed to read encrypted data"}}});r.ipcMain.handle("check-has-encrypted-data",async()=>{const n=c.join(r.app.getPath("userData"),"secureData.bin");try{return await l.promises.access(n,l.constants.F_OK),r.safeStorage.isEncryptionAvailable()?{success:!0}:{success:!1,message:"Data not available"}}catch{return{success:!1,message:"Failed to get encrypted data"}}});r.ipcMain.handle("delete-encrypted-data",async()=>{const n=c.join(r.app.getPath("userData"),"secureData.bin");try{return l.existsSync(n)?(l.unlinkSync(n),{success:!0,message:"Encrypted data deleted successfully."}):{success:!1,message:"File does not exist."}}catch(t){return console.error("Failed to delete encrypted data:",t),{success:!1,message:"Failed to delete encrypted data."}}});


TypeError: Cannot read properties of undefined (reading 'handle')
    at Object.<anonymous> (/Users/dariush/.nvm/versions/node/v22.4.1/lib/node_modules/devon-ui/.vite/build/main.js:1:1581)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49

Node.js v22.4.1
```
